###

# Get all brands
// @no-log
GET http://{{host}}:{{port}}/api/brands

###

# Get a brand by id
// @no-log
GET http://{{host}}:{{port}}/api/brands/acme

###

# Create a brand
// @no-log
POST http://{{host}}:{{port}}/api/brands
Content-Type: application/json

{
  "name": "ACME",
  "kind": "INDUSTRIAL",
  "status": "ACTIVE",
  "address": {
    "street_address": "123 Main St",
    "extended_address": "Suite 100",
    "city": "Springfield",
    "region": "IL",
    "postal_code": "62701",
    "country": "US"
  }
}
