###

# Get all railways
// @no-log
GET http://{{host}}:{{port}}/api/railways

###

# Get a railway by id
// @no-log
GET http://{{host}}:{{port}}/api/railways/fs

###

# Create a railway
POST http://{{host}}:{{port}}/api/railways
Content-Type: application/json

{
  "name": "FS",
  "abbreviation": "FS",
  "country": "IT",
  "status": "ACTIVE",
  "address": {
    "street_address": "123 Main St",
    "extended_address": "Suite 100",
    "city": "Springfield",
    "region": "IL",
    "postal_code": "62701",
    "country": "US"
  }
}
