name: Java CI with Gradle (Kotlin)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Check Java style
        run: ./gradlew spotlessJavaCheck

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Run tests with Gradle
        run: ./gradlew test

      - uses: actions/upload-artifact@v3
        with:
          name: Build Artifacts
          path: |
            **/build/reports
